import path from "node:path";
import fs from "node:fs";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

import mime from "mime";
import parseRange from "range-parser";
import { TemplatePath } from "@11ty/eleventy-utils";
import { escapeText } from "entities/escape";
import { createDebug } from "obug";

const require = createRequire(import.meta.url);
const debug = createDebug("Eleventy:DevServer");

// `server/` -> package root, where `client/` lives
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.join(__dirname, "..");

const BYTES_RANGE_REGEXP = /^ *bytes=/;

// Status codes that can be served from a custom `<status>.html` page in the output directory
export const CUSTOM_ERROR_PAGE_STATUSES = new Set([404, 500]);

// Common web file extensions and their content types
export const CONTENT_TYPES = {
  '.avif': 'image/avif',
  '.bmp': 'image/bmp',
  '.br': 'application/x-brotli',
  '.cjs': 'application/javascript',
  '.css': 'text/css',
  '.csv': 'text/csv',
  '.eot': 'application/vnd.ms-fontobject',
  '.eps': 'application/postscript',
  '.gif': 'image/gif',
  '.gz': 'application/gzip',
  '.htm': 'text/html',
  '.html': 'text/html',
  '.ico': 'image/x-icon',
  '.jpeg': 'image/jpeg',
  '.jpg': 'image/jpeg',
  '.js': 'application/javascript',
  '.json': 'application/json',
  '.m4v': 'video/mp4',
  '.map': 'application/json',
  '.md': 'text/markdown',
  '.mjs': 'application/javascript',
  '.mp3': 'audio/mpeg',
  '.mp4': 'video/mp4',
  '.ogg': 'audio/ogg',
  '.otf': 'font/otf',
  '.pdf': 'application/pdf',
  '.png': 'image/png',
  '.rss': 'application/rss+xml',
  '.svg': 'image/svg+xml',
  '.tar': 'application/x-tar',
  '.tif': 'image/tiff',
  '.tiff': 'image/tiff',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain',
  '.wasm': 'application/wasm',
  '.wav': 'audio/wav',
  '.webm': 'video/webm',
  '.webmanifest': 'application/manifest+json',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.xml': 'application/xml',
  '.yaml': 'application/yaml',
  '.yml': 'application/yaml',
  '.zip': 'application/zip',
};

/**
 * Static file resolution and serving.
 *
 * Deliberately synchronous: these run on whichever thread owns the HTTP server.
 * `fs.readFileSync`/`existsSync` are main-thread syscalls that bypass the libuv
 * threadpool, so they stay fast even while a build has the threadpool saturated.
 * Swapping these for `fs.promises` measures ~25x slower under that load.
 */
export default class StaticFiles {
  constructor(dir, options) {
    this.dir = dir;
    this.options = options;
    this.fileCache = {};
    this.passthroughAliases = {};
  }

  get logger() {
    return this.options.logger;
  }

  setOptions(options) {
    this.options = options;
  }

  // Allowed list of files that can be served from outside `dir`
  setAliases(aliases) {
    if(aliases) {
      this.passthroughAliases = aliases;
      debug( "Setting aliases (emulated passthrough copy) %O", aliases );
    }
  }

  matchPassthroughAlias(url) {
    let aliases = Object.assign({}, this.options.aliases, this.passthroughAliases);
    for(let targetUrl in aliases) {
      if(!targetUrl) {
        continue;
      }

      let file = aliases[targetUrl];
      if(url.startsWith(targetUrl)) {
        let inputDirectoryPath = file + url.slice(targetUrl.length);

        // e.g. addPassthroughCopy("img/") but <img src="/img/built/IdthKOzqFA-350.png">
        // generated by the image plugin (written to the output folder)
        // If they do not exist in the input directory, this will fallback to the output directory.
        if(fs.existsSync(inputDirectoryPath)) {
          return inputDirectoryPath;
        }
      }
    }
    return false;
  }

  isFileInDirectory(dir, file) {
    let relative = path.relative(path.resolve(dir), path.resolve(file));
    return relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
  }

  // Decodes each segment on its own, so an encoded separator (`%2f`, `%5c`) can't become a real one.
  #decodeUrlPath(urlPath) {
    return urlPath.split("/").map(segment => {
      let decoded;
      try {
        decoded = decodeURIComponent(segment);
      } catch(e) {
        throw new Error("Invalid path");
      }
      if(decoded === ".." || decoded.includes("/") || decoded.includes("\\")) {
        throw new Error("Invalid path");
      }
      return decoded;
    }).join("/");
  }

  getOutputDirFilePath(filepath, filename = "") {
    let decodedPath = this.#decodeUrlPath(filepath);

    let computedPath;
    if(filename === ".html") {
      // The root has no `resource.html` (it would sit beside the output directory)
      if(!decodedPath.split("/").some(Boolean)) {
        return;
      }

      // avoid trailing slash for filepath/.html requests
      let prefix = path.join(this.dir, decodedPath);
      if(prefix.endsWith(path.sep)) {
        prefix = prefix.substring(0, prefix.length - path.sep.length);
      }
      computedPath = prefix + filename;
    } else {
      computedPath = path.join(this.dir, decodedPath, filename);
    }

    if(!filename) { // is a direct URL request (not an implicit .html or index.html add)
      let alias = this.matchPassthroughAlias(decodedPath);

      if(alias) {
        if(!this.isFileInDirectory(".", alias)) {
          throw new Error("Invalid path");
        }

        return alias;
      }
    }

    // Check that the file is in the output path
    if(!this.isFileInDirectory(this.dir, computedPath)) {
      throw new Error("Invalid path");
    }

    return computedPath;
  }

  isOutputFilePathExists(rawPath) {
    return fs.existsSync(rawPath) && !TemplatePath.isDirectorySync(rawPath);
  }

  /* Use conventions documented here https://www.zachleat.com/web/trailing-slash/
   * resource.html exists:
   *    /resource matches
   *    /resource/ redirects to /resource
   * resource/index.html exists:
   *    /resource redirects to /resource/
   *    /resource/ matches
   * both resource.html and resource/index.html exists:
   *    /resource matches /resource.html
   *    /resource/ matches /resource/index.html
   */
  mapUrlToFilePath(url) {
    try {
      return this.#mapUrlToFilePath(url);
    } catch(e) {
      // Traversal attempts and malformed encodings
      if(e.message === "Invalid path") {
        return {
          statusCode: 404,
        };
      }
      throw e;
    }
  }

  #mapUrlToFilePath(url) {
    // Note: `localhost` is not important here, any host would work
    let u = new URL(url, "http://localhost/");
    url = u.pathname;

    // Remove PathPrefix from start of URL
    if (this.options.pathPrefix !== "/") {
      // Requests to root should redirect to new pathPrefix
      if(url === "/") {
        return {
          statusCode: 302,
          url: this.options.pathPrefix,
        }
      }

      // Requests to anything outside of root should fail with 404
      if (!url.startsWith(this.options.pathPrefix)) {
        return {
          statusCode: 404,
        };
      }

      url = url.slice(this.options.pathPrefix.length - 1);
    }

    let rawPath = this.getOutputDirFilePath(url);
    if (this.isOutputFilePathExists(rawPath)) {
      return {
        statusCode: 200,
        filepath: rawPath,
      };
    }

    let indexHtmlPath = this.getOutputDirFilePath(url, this.options.indexFileName);
    let indexHtmlExists = fs.existsSync(indexHtmlPath);

    let htmlPath = this.getOutputDirFilePath(url, ".html");
    let htmlExists = fs.existsSync(htmlPath);

    // /resource/ => /resource/index.html
    if (indexHtmlExists && url.endsWith("/")) {
      return {
        statusCode: 200,
        filepath: indexHtmlPath,
      };
    }
    // /resource => resource.html
    if (htmlExists && !url.endsWith("/")) {
      return {
        statusCode: 200,
        filepath: htmlPath,
      };
    }

    // /resource => redirect to /resource/
    if (indexHtmlExists && !url.endsWith("/")) {
      return {
        statusCode: 301,
        url: u.pathname + "/",
      };
    }

    // /resource/ => redirect to /resource
    if (htmlExists && url.endsWith("/")) {
      return {
        statusCode: 301,
        url: u.pathname.substring(0, u.pathname.length - 1),
      };
    }

    return {
      statusCode: 404,
    };
  }

  #readFile(filepath) {
    if(this.options.useCache && this.fileCache[filepath]) {
      return this.fileCache[filepath];
    }

    let contents = fs.readFileSync(filepath, {
      encoding: this.options.encoding,
    });

    if(this.options.useCache) {
      this.fileCache[filepath] = contents;
    }

    return contents;
  }

  readFile(filepath) {
    return this.#readFile(filepath);
  }

  /**
   * Used for the reload client only
   * @returns {String}
   */
  getFileContents(localpath, rootDir) {
    let filepath;
    let searchLocations = [];

    if(rootDir) {
      searchLocations.push(TemplatePath.absolutePath(rootDir, localpath));
    }

    // fallbacks for file:../ installations
    searchLocations.push(TemplatePath.absolutePath(PACKAGE_ROOT, localpath));

    for(let loc of searchLocations) {
      if(fs.existsSync(loc)) {
        filepath = loc;
        break;
      }
    }

    return this.#readFile(filepath);
  }

  getReloadClientContents() {
    return this.getFileContents("./client/reload-client.js");
  }

  getMorphdomPath() {
    return require.resolve("morphdom").replace("morphdom.js", "morphdom-esm.js");
  }

  /**
   * @param {String} data
   */
  sri(data) {
    return `sha512-${crypto.createHash("sha512").update(data).digest("base64")}`
  }

  getServerPath(pathname) {
    // duplicate slashes
    if(this.options.pathPrefix.endsWith("/") && pathname.startsWith("/")) {
      pathname = pathname.slice(1);
    }
    return `${this.options.pathPrefix}${pathname}`;
  }

  augmentContentWithNotifier(content, inlineContents = false, options = {}) {
    let { integrityHash, scriptContents } = options;
    if(!scriptContents) {
      scriptContents = this.getReloadClientContents();
    }
    if(!integrityHash) {
      integrityHash = this.sri(scriptContents);
    }

    let searchParams = new URLSearchParams();
    if(this.options.reloadPort) {
      searchParams.set("reloadPort", this.options.reloadPort);
    }

    let searchParamsStr = searchParams.size > 0 ? `?${searchParams.toString()}` : "";

    // This isn't super necessary because it's a local file, but it's included anyway
    let script = `<script type="module" integrity="${integrityHash}"${inlineContents ? `>${scriptContents}` : ` src="/${this.options.injectedScriptsFolder}/reload-client.js${searchParamsStr}">`}</script>`;

    if (content.includes("</head>")) {
      return content.replace("</head>", `${script}</head>`);
    }

    // If the HTML document contains an importmap, insert the module script after the importmap element
    let importMapRegEx = /<script type=\\?importmap\\?[^>]*>(\n|.)*?<\/script>/gmi;
    let importMapMatch = content.match(importMapRegEx)?.[0];

    if (importMapMatch) {
      return content.replace(importMapMatch, `${importMapMatch}${script}`);
    }

    // <title> is the only *required* element in an HTML document
    if (content.includes("</title>")) {
      return content.replace("</title>", `</title>${script}`);
    }

    // If you've reached this section, your HTML is invalid!
    // We want to be super forgiving here, because folks might be in-progress editing the document!
    if (content.includes("</body>")) {
      return content.replace("</body>", `${script}</body>`);
    }
    if (content.includes("</html>")) {
      return content.replace("</html>", `${script}</html>`);
    }
    if (content.includes("<!doctype html>")) {
      return content.replace("<!doctype html>", `<!doctype html>${script}`);
    }

    // Notably, works without content at all!!
    return (content || "") + script;
  }

  /**
   * Infer a content-type from a filepath.
   * @returns {string|undefined}
   */
  getFileContentType(filepath, res) {
    let contentType = res.getHeader("Content-Type");

    // Content-Type might be already set via middleware
    if (contentType) {
      return contentType;
    }

    const ext = path.extname(filepath).toLowerCase();

    // First check our common types
    if (CONTENT_TYPES[ext]) {
      contentType = CONTENT_TYPES[ext];
    } else {
      // Fallback to mime package for other types
      contentType = mime.getType(filepath);
    }

    if (!contentType) {
      return;
    }

    // Add charset for text-based content types
    const textTypes = [
      'text/',
      'text/html',
      'application/javascript',
      'application/json',
      'application/xml',
      'application/yaml',
      'application/x-www-form-urlencoded'
    ];

    // Check if the content type matches any text-based MIME types to determine if charset should be added
    if (textTypes.some(type => contentType.startsWith(type))) {
      contentType = `${contentType}; charset=${this.options.encoding}`;
    }

    return contentType;
  }

  renderFile(filepath, res) {
    let contents = fs.readFileSync(filepath);
    let contentType = this.getFileContentType(filepath, res);

    for(const [key, value] of Object.entries(this.options.headers)){
      res.setHeader(key, value);
    }

    if (!contentType) {
      return res.end(contents);
    }

    res.setHeader("Content-Type", contentType);

    if (contentType.startsWith("text/html")) {
      // the string is important here, wrapResponse expects strings internally for HTML content (for now)
      return res.end(contents.toString());
    }

    return res.end(contents);
  }

  /**
   * @param {String} type
   * @param {number} size
   * @param {{start: number, end: number} | undefined} range
   */
  #contentRange(type, size, range) {
    return type + ' ' + (range ? range.start + '-' + range.end : '*') + '/' + size
  }

  /**
   * @param {import('node:http').IncomingMessage} req
   * @param {import('node:http').OutgoingMessage} res
   * This runs at the end of the middleware chain
   */
  // Serves an allowed `<status>.html` from the output directory if it exists, otherwise a minimal error page.
  sendError(req, res, statusCode, message) {
    if(res.headersSent) {
      return res.end();
    }

    if(CUSTOM_ERROR_PAGE_STATUSES.has(statusCode)) {
      let customPath = this.getOutputDirFilePath(`${statusCode}.html`);
      if(this.isOutputFilePathExists(customPath)) {
        res.statusCode = statusCode;
        return this.renderFile(customPath, res);
      }
    }

    let body = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>${escapeText(message)}</pre>\n</body>\n</html>\n`;

    // Headers from upstream middleware don't describe this body
    for(let name of ["Content-Encoding", "Content-Language", "Content-Range"]) {
      res.removeHeader(name);
    }

    res.statusCode = statusCode;
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.setHeader("X-Content-Type-Options", "nosniff");

    if(req.method === "HEAD") {
      return res.end();
    }

    // A string, so the live reload client is injected
    res.end(body);
  }

  serve(req, res) {
    // middleware (maybe a serverless request) already set a body upstream, skip this part
    if(!res._shouldForceEnd) {
      let match = this.mapUrlToFilePath(req.url);
      debug( req.url, match );

      if (match) {
        if (match.statusCode === 200 && match.filepath) {
          // Content-Range request, probably Safari trying to stream video
          // If the client includes an If-Range header,
          // serve them the whole thing. We don't include
          // last-modified or etags headers, so these
          // requests are invalid.
          if (BYTES_RANGE_REGEXP.test(req.headers.range) && !req.headers['if-range'])  {
            return fs.stat(match.filepath, (err, stat) => {
              if (err) {
                res.statusCode = 404;
                res.end('File not found');
                return;
              }

              let contentType = this.getFileContentType(match.filepath, res);
              let len = stat.size;

              const ranges = parseRange(len, req.headers.range, {
                combine: true
              })

              // Tell clients that they can send ranges.
              res.setHeader('Accept-Ranges', 'bytes');
              res.setHeader('Cache-Control', 'public, max-age=0');
              if (contentType) {
                res.setHeader("Content-Type", contentType);
              }

              // unsatisfiable
              if (ranges === -1) {
                // 416 Requested Range Not Satisfiable
                res.statusCode = 416;
                res.setHeader('Content-Range', this.#contentRange('bytes', len))
                return res.end();
              } else if (ranges !== -2 && ranges.length === 1) {
              // valid (syntactically invalid/multiple ranges are treated as a regular response)
                // Content-Range
                res.statusCode = 206;
                res.setHeader('Content-Range', this.#contentRange('bytes', len, ranges[0]))

                // adjust for requested range
                let start = ranges[0].start
                len = ranges[0].end - ranges[0].start + 1
                let end = ranges[0].end
                res.setHeader('Content-Length', len)
                if (req.method === 'HEAD') {
                  res.end()
                  return
                }
                const stream = fs.createReadStream(match.filepath, {
                  start, end
                });
                stream.pipe(res);
                const cleanup = () => {
                  stream.destroy();
                  res.destroy();
                }
                res.on('close', cleanup);
                stream.on('error', cleanup);
                stream.on('end', cleanup);
              } else {
                // Just send multi-range requests as full files.
                return this.renderFile(match.filepath, res);
              }
            });
          }
          return this.renderFile(match.filepath, res);
        }

        // Redirects, usually for trailing slash to .html stuff
        if (match.url) {
          res.statusCode = match.statusCode;
          res.setHeader("Location", match.url);
          return res.end();
        }

        let raw404Path = this.getOutputDirFilePath("404.html");
        if(match.statusCode === 404 && this.isOutputFilePathExists(raw404Path)) {
          res.statusCode = match.statusCode;
          return this.renderFile(raw404Path, res);
        }
      }
    }

    if(res.body && !res.bodyUsed) {
      if(res._shouldForceEnd) {
        res.end();
      } else {
        let message = "A response was never written to the stream. Are you missing a server middleware with `res.end()`?";
        this.logger.error(`HTTP 500: ${message}`);
        return this.sendError(req, res, 500, message);
      }
    }

    let pathname;
    try {
      pathname = new URL(req.url, "http://localhost/").pathname;
    } catch(e) {
      pathname = "resource";
    }
    return this.sendError(req, res, 404, `Cannot ${req.method} ${pathname}`);
  }
}
